# Generated by Django 4.2 on 2026-03-25 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('location', models.CharField(choices=[('head_office', 'Head Office'), ('factory', 'Factory')], max_length=20)),
                ('ot_applicable', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Designation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.department')),
            ],
        ),
        migrations.CreateModel(
            name='SalaryStructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basic_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('da_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ot_rate_per_hour', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('pf_applicable', models.BooleanField(default=True)),
                ('esi_applicable', models.BooleanField(default=True)),
                ('department', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='employees.department')),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=150)),
                ('employment_type', models.CharField(choices=[('permanent', 'Permanent'), ('contract', 'Contract'), ('daily_wage', 'Daily Wage')], max_length=20)),
                ('shift', models.CharField(choices=[('day', 'Day Shift'), ('night', 'Night Shift')], max_length=10)),
                ('date_of_joining', models.DateField()),
                ('gross_salary', models.DecimalField(decimal_places=2, max_digits=10)),
                ('daily_wage_rate', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('bank_account', models.CharField(max_length=20)),
                ('bank_ifsc', models.CharField(max_length=15)),
                ('bank_name', models.CharField(max_length=100)),
                ('pan_number', models.CharField(blank=True, max_length=10)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.department')),
                ('designation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.designation')),
            ],
        ),
    ]
